### ISSUE TITLE
Capability to add labels on the arrows

### ISSUE THREAD

**Issue by Ankita35** [sasza2/arrows#11]
I think the label should be added under the list of attributes for the Arrow Component. It will make the design look more complete. Or maybe give a capability to put an event listener on the component.

**Comment by sasza2** [comment]
Check 'onChange' method with label example:
- here https://github.com/sasza2/arrows/tree/master/test/labels
- and here https://codesandbox.io/s/suspicious-jepsen-h0p9e

**Comment by Ankita35** [comment]
Great! I'll try in react-arrows library though. Do you have a working example on this sandbox https://codesandbox.io/s/charming-nobel-35voq ?

Also, how can I use <Arrow /> to draw a small legend to show on the top about the different color of the arrows and with the name.

Like from the image, I want to show that the blue color is for StepStartOnStepComplete and all the other colors too on the right corner with small arrows with same stroke and width. 

Hope my question is clear.

**Comment by sasza2** [comment]
There's also 'onChange' in react-arrows https://codesandbox.io/s/laughing-keldysh-1fnq4

second part of your question: I think you must read something about CSS **position:** absolute / fixed combined with **top:** and **right:**
