### ISSUE TITLE
FEATURE REQUEST: tail property

### ISSUE THREAD

**Issue by drush** [sasza2/arrows#16]
Clone the head implementation for a tail property for the origin of the arrow.

**Comment by sasza2** [comment]
could you show example image of what you trying to achieve?

**Comment by drush** [comment]
<img width="158" alt="image" src="https://user-images.githubusercontent.com/109985/99463235-2bf70780-28ea-11eb-82b9-a231ad39b105.png">

**Comment by sasza2** [comment]
@drush now you can pass an array to prop `head`, example at https://codesandbox.io/s/cool-pine-zqrpg
