### ISSUE TITLE
Question: Is is possible to auto calculate default translation / direction ?

### ISSUE THREAD

**Issue by laurent67100** [sasza2/arrows#17]
Hi! First thanks for this great library!
I was wondering if it is possible to auto calculate default translation and from/to direction based on the position of the elements one to each other?

In this example, since the `to` element is on the bottom right of the `from` element, default translation / direction could be:
- for the from element: direction = BOTTOM, translation = [0,1]
- for the to element: direction = TOP, translation = [0,-1]

Thanks!

![image](https://user-images.githubusercontent.com/8155684/99554234-f525fd80-298c-11eb-844e-6976cdd3fa94.png)

**Comment by sasza2** [comment]
hi, you're welcome. yes. it is, but be patient - i'm currently rewriting it to preact

**Comment by sasza2** [comment]
@laurent67100 it's done. please, check the newest version and see examples/auto
