### ISSUE TITLE
Location and Direction of the Arrow head

### ISSUE THREAD

**Issue by edsuna** [sasza2/arrows#18]
I forked your example sandbox from the readme to show the problems I am having. My sandbox is https://codesandbox.io/s/pensive-platform-sgwby You can see that the arrow head does not touch the circle when specifying TOP_LEFT. Also, the direction of the arrow head is not perpendicular to the line of the arrow.

Do you have any way that I could specify the transform parameter for the arrow head to make it be perpendicular? If I change the transform of the arrow_head class directly via inspect as follows:
`<g class="arrow__head" transform="rotate(45, 200, 160), translate(200, 160)"><path d="M-10 -10 L0 0 L-10 10 Z"></path></g>`
then the head rotates properly but I did not see a way to pass that in to affect the code. The degree computation seems to be done in head.js.

Also, is there a way to have the arrow extend to touch the circle rather than stopping at the border of the div?

Thanks

**Comment by sasza2** [comment]
Hi, for now you can try https://codesandbox.io/s/charming-kowalevski-ib047
I've changed duration in head and add #to-inner element. I'll fix it after I finish rewriting it to preact. Thanks

**Comment by edsuna** [comment]
Thank you I was able to make that work.
