### ISSUE TITLE
Adding Tail same as header

### ISSUE THREAD

**Issue by Mytheses** [sasza2/arrows#30]
Hi, Is it possible to add the header on the tail side as well? 
![Expected Output](https://user-images.githubusercontent.com/62224193/119318577-15bc7080-bcac-11eb-827c-7ec7973b20ab.png)
Thanks in advance.

**Comment by sasza2** [comment]
yes, it is. example - https://codesandbox.io/s/zen-brook-5vcu7 @Mytheses
