### ISSUE TITLE
Refresh time

### ISSUE THREAD

**Issue by Catman155** [sasza2/arrows#35]
Hi, I wish there was an option to set the observer refresh time. I'm currently making something where you have to move boxes with lines between them. but it lags with the current set 150ms interval

**Comment by sasza2** [comment]
hi, from now you can use `updateDelay` prop like

```js
arrowCreate({
  [...],
  updateDelay: 50, // ms
})
```

**Comment by Catman155** [comment]
cool, thx for the quick fix
