### ISSUE TITLE
Anchor translation offset

### ISSUE THREAD

**Issue by JackMorganNZ** [sasza2/arrows#44]
Is there a way (or trick) to set a offset for the anchor translation on a start on end node?
This is translation in the sense of moving on x/y coords of the elements position, rather than translation of the beizer curves.

For example, I want to start the arrow at the location of the red cross (under the last digit):
![image](https://user-images.githubusercontent.com/8001048/193956220-94bcfdc3-f83f-4c79-9dda-537312da42e6.png)

At the moment, my strategy is to create a HTML element, that is absolutely positioned and hidden with CSS and anchor to that.

Thank you for a great package!

**Comment by JackMorganNZ** [comment]
Update: Using a absolutely position hidden element works really well, here it is with a custom tail:

![image](https://user-images.githubusercontent.com/8001048/193962495-f9ec2833-f2a4-4304-beb8-f214d144d2d2.png)

**Comment by sasza2** [comment]
hi, you're welcome! your solution looks really nice

**Comment by JackMorganNZ** [comment]
Thanks @sasza2. I'll close this issue as this solution achieves the desired outcome.
