### ISSUE TITLE
No need for the checked-in /dist/main.js

### ISSUE THREAD

**Issue by jan-dolejsi** [sasza2/arrows#55]
Do you have a reason for committing the transpiled `main.js`? 
If you want it available for loading into simple websites, they could always pull it from places like [https://www.unpkg.com/arrows-svg@1.7.0/dist/main.js](https://www.unpkg.com/arrows-svg@1.7.0/dist/main.js) 

Not quite an _issue_. It does not change anything for the NPM package content, because `npm pack` should build it in the pipeline. Oh, hang on. I do not see the pipeline in the repo. But the npm `prepack` script should ensure that. That way you can be sure the `main.js` is up to date with the `*.ts`.

**Comment by sasza2** [comment]
thanks for PR. I just added pipeline for master branch, so now anything merged with new version should be automatically published
