### ISSUE TITLE
Issues importing the package using vite and svelte

### ISSUE THREAD

**Issue by r59q** [sasza2/arrows#58]
First off, thank you for this amazing package !

I have just installed the package for my project using Vite and Svelte. I get the error

```ts
import { IArrow } from 'arrows-svg/types/interfaces/IArrow';

....

Internal server error: Failed to resolve import "arrows-svg/types/interfaces/IArrow" from
"src/components/component.svelte". Does the file exist?
```
in vscode i get the syntax error `Module '"arrows-svg/types/interfaces/IArrow"' has no exported member 'IArrow'.ts(2305)`

when i attempt to import the IArrow type

Adding the file extension fixes the issue

```ts
 import type { IArrow } from 'arrows-svg/types/interfaces/IArrow.d.ts';
```
but then i get the error in vscode `Module '"arrows-svg/types/interfaces/IArrow.d.ts"' has no exported member 'IArrow'.ts(2305)
`

and i have to add `// @ts-ignore` to remove it

Anyhow it would be nice to be able to import the type from another namespace by declaring the module in the d.ts files

```ts
declare module 'arrows-svg' {
    export interface IArrow {
        node: DocumentFragment;
        clear: () => void;
    }
}
```
so that one could just import
```ts
 import { IArrow } from 'arrows-svg';
```
directly. This would also fix the above mentioned issues :pray:

**Comment by sasza2** [comment]
@r59q please check newest version https://www.npmjs.com/package/arrows-svg/v/1.8.0
it should exports IArrow as you mentioned

**Comment by r59q** [comment]
@sasza2 Thank you for such a quick response, i will mark it as closed :+1:
