### ISSUE TITLE
A way to set a gap

### ISSUE THREAD

**Issue by datanotion** [sasza2/arrows#8]
Thank you for your great component!  Is there a way to set a gap between the start/end of the arrow so it doesn't actually touch the element?  Like:

![image](https://user-images.githubusercontent.com/4722782/80315684-75e59800-87b6-11ea-9395-29bc15eb553a.png)

**Comment by sasza2** [comment]
Hi! you're welcome. 

The easiest way I can think of is just add some padding inside of children elements like:

https://codesandbox.io/s/icy-water-5s43v

What do you think?

**Comment by datanotion** [comment]
Thank should work - thank you!
